"""empty message

Revision ID: 6ca51ae25253
Revises: 3d2111442635
Create Date: 2018-07-26 12:29:00.377192

"""

# revision identifiers, used by Alembic.
revision = '6ca51ae25253'
down_revision = '3d2111442635'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_clients',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('is_authorized', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.alter_column('article_media', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('article_media', 'media_type',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('article_media', 'media_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('article_tags', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('article_tags', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('articles', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('articles', 'date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('articles', 'md5hash',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('articles', 'medium_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('articles', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('articles', 'url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.create_unique_constraint(None, 'articles', ['url'])
    op.create_unique_constraint(None, 'articles', ['md5hash'])
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'clients', ['name'])
    op.alter_column('mediums', 'medium_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mediums', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mediums', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'mediums', ['url'])
    op.create_unique_constraint(None, 'mediums', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mediums', type_='unique')
    op.drop_constraint(None, 'mediums', type_='unique')
    op.alter_column('mediums', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mediums', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mediums', 'medium_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'clients', type_='unique')
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_constraint(None, 'articles', type_='unique')
    op.alter_column('articles', 'url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('articles', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('articles', 'medium_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('articles', 'md5hash',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('articles', 'date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('articles', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('article_tags', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('article_tags', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('article_media', 'media_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('article_media', 'media_type',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('article_media', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('user_clients')
    # ### end Alembic commands ###
