"""empty message

Revision ID: a8f5175c8222
Revises: 1fb7c6da302
Create Date: 2018-07-23 15:56:17.537688

"""

# revision identifiers, used by Alembic.
revision = 'a8f5175c8222'
down_revision = '1fb7c6da302'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('medium_type', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('charset', sa.String(length=8), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medium')
    # ### end Alembic commands ###
